name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Setup mise
        uses: jdx/mise-action@v4.3.0

      - name: Build for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -ldflags "-X main.Version=${{ github.event.release.tag_name }} -X main.Build=${{ github.sha }}" -o bin/commits-for-version-linux-amd64 .

      - name: Upload binary to release
        uses: softprops/action-gh-release@v3.0.3
        with:
          files: bin/commits-for-version-linux-amd64
